name: Deploy React APP

on:
  push:
    branches:
      - master 
  pull_request:
    branches:
      - master 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build react app
    steps:
      - uses: actions/checkout@v3
      - name: list the files
        run: |
          cd $GITHUB_WORKSPACE
          ls

                    