name: Deploy React APP

on:
  push:
    branches:
      - master 
  pull_request:
    branches:
      - master 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    name: Build react app
    steps:
      - uses: actions/checkout@v3
      - name: list the files
        run: |
          cd $GITHUB_WORKSPACE
          ls
      - name: Use node version ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build React App
        run: |
          cd $GITHUB_WORKSPACE\my-app
          npm ci
          npm run build --if-present
          ls

                    